In [97]:
#讀入向量空間模型，以訓練學習演算法自動判斷類別，實驗多種演算法，以交互驗證測試模型準確率
#Big Data & Business Analytics, Willie Yang, National Taiwan University

In [1]:
from scipy import sparse
X = sparse.load_npz("limit_model.npz") #讀入稀疏矩陣
X

<7393x108 sparse matrix of type '<class 'numpy.float64'>'
	with 173482 stored elements in Compressed Sparse Row format>

In [3]:
import numpy as np

y=[] #用以儲存已知類別
for i in range(4194): #已知前4194篇為漲停，標記為看漲 (此為取巧權宜作法)
  y.append(['看漲'])
for i in range(3199): #已知後3199篇為跌停，標記為看跌
  y.append(['看跌'])
y=np.ravel(y) #轉換成array避免警告訊息

In [4]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()

from sklearn.model_selection import cross_val_score
scores = cross_val_score(classifier,X,y,cv=5,scoring='accuracy') #交叉驗證，計算準確率
print(scores)
print("Avg. Accuracy:",scores.mean())

[0.56524679 0.56186613 0.51859364 0.56562923 0.53924222]
Avg. Accuracy: 0.550115601277607


In [5]:
from sklearn.tree import DecisionTreeClassifier                          
classifier = DecisionTreeClassifier(criterion="entropy")

from sklearn.model_selection import cross_val_score
scores = cross_val_score(classifier,X,y,cv=5,scoring='accuracy') #交叉驗證，計算準確率
print(scores)
print("Avg. Accuracy:",scores.mean())

[0.5571332  0.51994591 0.51250845 0.5135318  0.51217862]
Avg. Accuracy: 0.5230595957294775


In [6]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=7)

from sklearn.model_selection import cross_val_score
scores = cross_val_score(classifier,X,y,cv=5,scoring='accuracy') #交叉驗證，計算準確率
print(scores)
print("Avg. Accuracy:",scores.mean())

[0.56795132 0.51521298 0.5240027  0.51691475 0.52368065]
Avg. Accuracy: 0.5295524807842039


In [8]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear')

from sklearn.model_selection import cross_val_score
scores = cross_val_score(classifier,X,y,cv=5,scoring='accuracy') #交叉驗證，計算準確率
print(scores)
print("Avg. Accuracy:",scores.mean())

# 這個要特別久

[0.56659905 0.56727519 0.53820149 0.567659   0.54533153]
Avg. Accuracy: 0.5570132509165302


In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

classifier = RandomForestClassifier(random_state=42)
scores = cross_val_score(classifier, X, y, cv=5, scoring='accuracy')
print(scores)
print("Avg. Accuracy:", scores.mean())

# random forest

[0.60513861 0.54699121 0.52738337 0.55953992 0.54194858]
Avg. Accuracy: 0.5562003365108817
